apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: europe-central2-docker.pkg.dev/melita-project-450315/melita-repo/order-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_ENABLED
              value: "false"
            - name: SPRING_PROFILES_ACTIVE
              value: dev