name: Build and Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Setup JDK
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      # Authenticate with Google Cloud
      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Configure Docker to use Artifact Registry
      - name: Configure Docker to use Artifact Registry
        run: gcloud auth configure-docker ${{ secrets.GAR_LOCATION }}-docker.pkg.dev

      # Build the Maven project
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # Build and Push the Docker Image
      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.GAR_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.REPO_NAME }}/order-service:latest .
          docker push ${{ secrets.GAR_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.REPO_NAME }}/order-service:latest

      # List images in Artifact Registry (optional for debugging)
      - name: List Images in Artifact Registry
        run: gcloud artifacts docker images list ${{ secrets.GAR_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.REPO_NAME }}

  deploy:
    name: Deploy to GKE
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Step 1 - Checkout Repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2 - Authenticate with Google Cloud
      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Step 3 - Update and install dependencies (gcloud, kubectl, auth-plugin)
      - name: Install gke-gcloud-auth-plugin and kubectl
        run: |
          sudo apt-get update
          sudo apt-get install -y google-cloud-cli-gke-gcloud-auth-plugin kubectl

      # Step 4 - Configure kubectl to connect with GKE
      - name: Configure kubectl
        run: |
          export USE_GKE_GCLOUD_AUTH_PLUGIN=True
          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} --region ${{ secrets.GKE_REGION }}

      # Step 5 - Apply Kubernetes manifests
      - name: Deploy to GKE
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
