apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: europe-west1-docker.pkg.dev/melita-project-450315/order-taking-api/order-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/orderdb"
            - name: SPRING_DATASOURCE_USERNAME
              value: "orderuser"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "orderpassword"
